Fifth module/first task
PrimoTibalt/DotNetMentoringProgram pull request #10
Opened 2021-05-09 04:36 UTC by PrimoTibalt

2021-05-13 19:30 UTC, alexander-trishin requested changes
Hi Anton,

In general it works 😃 But there are a few issues:
- Long rows are unreadable
- Arguments of public methods were not verified
- Some queries are very ineffective

2021-05-13 19:30 UTC, alexander-trishin commented on ModuleFifthTasks/Task1/LinqTask.cs
>          public static IEnumerable<Customer> Linq1(IEnumerable<Customer> customers, decimal limit)
Please, always verify arguments in public methods for invalid values like `null`.

2021-05-13 19:30 UTC, alexander-trishin commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return customers.Select((customer, num) => new ValueTuple<Customer, IEnumerable<Supplier>>(customer, suppliers.Where(supplier => supplier.Country == customer.Country && supplier.City == c
Long lines are hard-readable.

```suggestion
            return customers.Select(customer =>
            (
                customer,
                suppliers.Where(supplier => supplier.Country == customer.Country
                     && supplier.City == customer.City)
            ));
```

2021-05-13 19:30 UTC, alexander-trishin commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return customers.Where(customer => customer.Orders.Count() > 0).Select(customer => new ValueTuple<Customer, DateTime>(customer, customer.Orders.Min(order => order.OrderDate)));
Do not forget to use line breaks 😃 Also **please note** that `.Any()` is more effective than `.Count() > 0` becase it will stop iteration over collection after the first element.

```suggestion
           return customers
                .Where(customer => customer.Orders.Any())
                .Select(customer => (customer, customer.Orders.Min(order => order.OrderDate)));
```

2021-05-13 19:30 UTC, alexander-trishin commented on ModuleFifthTasks/Task1/LinqTask.cs
> +                .ThenByDescending(tuple => tuple.customer.Orders.Sum(order => order.Total));
You forgot about `customer.CompanyName`

2021-05-13 19:30 UTC, alexander-trishin commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return products.GroupBy(product => product.Category).Select(category => new Linq7CategoryGroup { Category = category.Key }).Join(
This is highly over-engineered. Here is more simple example:

```c#
return products
	.GroupBy(product => product.Category, (category, products) => new Linq7CategoryGroup()
	{
		Category = category,
		UnitsInStockGroup = products.GroupBy(
			product => product.UnitsInStock,
			product => product.UnitPrice,
			(unitsInStock, groupedProducts) => new Linq7UnitsInStockGroup()
			{
				UnitsInStock = unitsInStock,
				Prices = groupedProducts.OrderBy(price => price)
			})
	});
```

2021-05-13 19:30 UTC, alexander-trishin commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return new List<ValueTuple<decimal, IEnumerable<Product>>>
Can be solved in more effective way using single `.Where()` and single `.GroupBy()`

2021-05-15 01:51 UTC, PrimoTibalt commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return new List<ValueTuple<decimal, IEnumerable<Product>>>
Fixed in d71bf5c.

2021-05-15 01:51 UTC, PrimoTibalt commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return products.GroupBy(product => product.Category).Select(category => new Linq7CategoryGroup { Category = category.Key }).Join(
Fixed in d71bf5c.

2021-05-15 01:51 UTC, PrimoTibalt commented on ModuleFifthTasks/Task1/LinqTask.cs
> +                .ThenByDescending(tuple => tuple.customer.Orders.Sum(order => order.Total));
Fixed in d71bf5c.

2021-05-15 01:51 UTC, PrimoTibalt commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return customers.Where(customer => customer.Orders.Count() > 0).Select(customer => new ValueTuple<Customer, DateTime>(customer, customer.Orders.Min(order => order.OrderDate)));
Fixed in d71bf5c.

2021-05-15 01:51 UTC, PrimoTibalt commented on ModuleFifthTasks/Task1/LinqTask.cs
> +            return customers.Select((customer, num) => new ValueTuple<Customer, IEnumerable<Supplier>>(customer, suppliers.Where(supplier => supplier.Country == customer.Country && supplier.City == c
Fixed in d71bf5c.

2021-05-15 01:52 UTC, PrimoTibalt commented on ModuleFifthTasks/Task1/LinqTask.cs
>          public static IEnumerable<Customer> Linq1(IEnumerable<Customer> customers, decimal limit)
Fixed in d71bf5c.

2021-05-21 08:51 UTC, alexander-trishin approved these changes

2021-05-24 22:49 UTC, merged